version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    # environment:
    #   - discovery.type=single-node
    #   - xpack.security.enabled=false
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      - xpack.security.authc.api_key.enabled=true
      - xpack.fleet.enabled=true
      - xpack.agent.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.ingestManager.enabled=true      
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/pipeline.yml:/usr/share/logstash/config/pipelines.yml
    ports:
      - "5044:5044"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    # environment:
    #   - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.fleet.agents.enabled=true
      - xpack.security.enabled=true
      - xpack.fleet.packages=["endpoint"]    
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/logs:/usr/share/filebeat/logs:ro
    command: ["sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e"]  
    depends_on:
      - logstash

  endpoint-agent:
    image: ubuntu:20.04
    container_name: endpoint-agent
    tty: true
    stdin_open: true
    command: [ "bash", "-c", "while true; do sleep 1000; done" ]
      
      
